version: '3'
services:
  python:
    container_name: 'python.cpu.akitenkrad-blog'
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    tty: true
    volumes:
      - ./:/workplace:cached
      - /Users/akitenkrad/.ssh:/root/.ssh
    environment:
      TZ: Asia/Tokyo
    working_dir: /workplace
    ports:
      - 1313:1313
