version: '3'
services:
  python:
    container_name: 'python.cpu.akitenkrad-blog'
    image: akitenkrad/python.cpu.arm64:latest
    user: root
    tty: true
    volumes:
      - ./:/workplace
      - data:/data
      - /Users/akitenkrad/.ssh:/root/.ssh
    environment:
      TZ: Asia/Tokyo
    working_dir: /workplace
    ports:
      - 1313:1313
volumes:
  data:
    name: data
    external: true
