name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

env:
  SLACK_USERNAME: "GitHub Actions"
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: cd src && hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_dir: ./docs

      - name: Slack Notification on Success
        uses: rtCamp/action-slack-notify@v2
        if : ${{ success() }}
        env:
          SLACK_TITLE: "Deployed Successfully"
          SLACK_COLOR: good
          SLACK_MESSAGE: "Deployed akitenkrad's blog Successfully!!!"

      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2
        if : ${{ failure() }}
        env:
          SLACK_TITLE: "Deploy Failed"
          SLACK_COLOR: danger
          SLACK_MESSAGE: "Failed to deploy akitenkrad's blog!!!"